-- MySQL Script generated by MySQL Workbench
-- 01/29/16 17:22:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema userCram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema userCram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `userCram` DEFAULT CHARACTER SET utf8 ;
USE `userCram` ;

-- -----------------------------------------------------
-- Table `userCram`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `newsletter` TINYINT(1) NOT NULL,
  `notification` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`flash_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`flash_cards` (
  `flash_cards_id` INT NOT NULL AUTO_INCREMENT,
  `flash_cards_name` VARCHAR(45) NOT NULL,
  `flash_cards_discription` VARCHAR(400) NULL,
  `flash_card_tag` VARCHAR(45) NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`flash_cards_id`),
  UNIQUE INDEX `flash_cards_id_UNIQUE` (`flash_cards_id` ASC),
  INDEX `fk_flash_cards_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_flash_cards_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `userCram`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`favorites` (
  `user_user_id` INT NOT NULL,
  `flash_cards_flash_cards_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `flash_cards_flash_cards_id`),
  INDEX `fk_user_has_flash_cards_flash_cards1_idx` (`flash_cards_flash_cards_id` ASC),
  INDEX `fk_user_has_flash_cards_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_flash_cards_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `userCram`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_flash_cards_flash_cards1`
    FOREIGN KEY (`flash_cards_flash_cards_id`)
    REFERENCES `userCram`.`flash_cards` (`flash_cards_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`user_flash_cards_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`user_flash_cards_results` (
  `user_user_id` INT NOT NULL,
  `flash_cards_flash_cards_id` INT NOT NULL,
  `correct_guesses` INT NOT NULL DEFAULT 0,
  `date` DATE NOT NULL,
  `total_guesses` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_user_id`, `flash_cards_flash_cards_id`),
  INDEX `fk_user_has_flash_cards_flash_cards3_idx` (`flash_cards_flash_cards_id` ASC),
  INDEX `fk_user_has_flash_cards_user2_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_user_has_flash_cards_user2`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `userCram`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_flash_cards_flash_cards3`
    FOREIGN KEY (`flash_cards_flash_cards_id`)
    REFERENCES `userCram`.`flash_cards` (`flash_cards_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`flash_cards_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`flash_cards_has_tags` (
  `flash_cards_flash_cards_id` INT NOT NULL,
  `tags_tag_id` INT NOT NULL,
  PRIMARY KEY (`flash_cards_flash_cards_id`, `tags_tag_id`),
  INDEX `fk_flash_cards_has_tags_tags1_idx` (`tags_tag_id` ASC),
  INDEX `fk_flash_cards_has_tags_flash_cards1_idx` (`flash_cards_flash_cards_id` ASC),
  CONSTRAINT `fk_flash_cards_has_tags_flash_cards1`
    FOREIGN KEY (`flash_cards_flash_cards_id`)
    REFERENCES `userCram`.`flash_cards` (`flash_cards_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flash_cards_has_tags_tags1`
    FOREIGN KEY (`tags_tag_id`)
    REFERENCES `userCram`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `userCram`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `userCram`.`questions` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(500) NOT NULL,
  `answer` VARCHAR(500) NOT NULL,
  `flash_cards_flash_cards_id` INT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_questions_flash_cards1_idx` (`flash_cards_flash_cards_id` ASC),
  CONSTRAINT `fk_questions_flash_cards1`
    FOREIGN KEY (`flash_cards_flash_cards_id`)
    REFERENCES `userCram`.`flash_cards` (`flash_cards_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
